# This is the configuration profile for the Dardel HPC system
# Read more about the available partitions at https://www.pdc.kth.se/support/documents/run_jobs/job_scheduling.html#dardel-partitions
# and about the compute nodes at https://www.pdc.kth.se/support/documents/run_jobs/job_scheduling.html#dardel-compute-nodes

# Update <your-slurm-account> under default-resources to your own slurm compute account
default-resources: 
  slurm_account: naiss2024-5-207
  slurm_partition: shared
  runtime: 240

# The settings below define command line flags for snakemake
keep-going: True
printshellcmds: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 200
latency-wait: 5
executor: slurm