[project]
name = "neeat-benchmark"
version = "0.1.0"
description = "Pixi project for running neeat benchmark on dardel"
authors = ["johnne <john.sundh@scilifelab.se>"]
channels = ["conda-forge", "bioconda", "main", "r", "msys2", "cduvallet"]
platforms = ["linux-64"]

[system-requirements]
linux="3.10.0"

[dependencies]
python = "*"
'r-data.table' = "*"
r-ape = "*"
r-seqinr = "*"
mafft = "*"
pal2nal = "*"
pandas = "*"
snakemake = "*"

[pypi-dependencies]
snakemake-executor-plugin-slurm = "*"